//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersGoods.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsersGoods.Web.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отфильтровать.
        /// </summary>
        public static string ActionFilter {
            get {
                return ResourceManager.GetString("ActionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить фильтр.
        /// </summary>
        public static string ActionResetFilter {
            get {
                return ResourceManager.GetString("ActionResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string ActionSearch {
            get {
                return ResourceManager.GetString("ActionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество записей.
        /// </summary>
        public static string CountRecords {
            get {
                return ResourceManager.GetString("CountRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string GoodAmount {
            get {
                return ResourceManager.GetString("GoodAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отфильтровать товары по цене.
        /// </summary>
        public static string GoodAmountFilter {
            get {
                return ResourceManager.GetString("GoodAmountFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование товара.
        /// </summary>
        public static string GoodName {
            get {
                return ResourceManager.GetString("GoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наиболее покупаемый товар.
        /// </summary>
        public static string GoodTop {
            get {
                return ResourceManager.GetString("GoodTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string MenuGoods {
            get {
                return ResourceManager.GetString("MenuGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записей не найдено.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поз..
        /// </summary>
        public static string PositionShort {
            get {
                return ResourceManager.GetString("PositionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество покупок.
        /// </summary>
        public static string PurchaseCount {
            get {
                return ResourceManager.GetString("PurchaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего куплено на сумму.
        /// </summary>
        public static string PurchaseTotalAmount {
            get {
                return ResourceManager.GetString("PurchaseTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to руб..
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупки пользователя.
        /// </summary>
        public static string UserCardGoods {
            get {
                return ResourceManager.GetString("UserCardGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары, купленные пользователем.
        /// </summary>
        public static string UserGoods {
            get {
                return ResourceManager.GetString("UserGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купил на сумму.
        /// </summary>
        public static string UserTotalAmount {
            get {
                return ResourceManager.GetString("UserTotalAmount", resourceCulture);
            }
        }
    }
}
